# Generated by Django 4.2.2 on 2023-12-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_highscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighScore',
        ),
    ]
