# Generated by Django 4.2.2 on 2023-12-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_highscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='company_name',
        ),
    ]
